#!/bin/bash
LOGFILE=test.log
APACHE_HOME=/usr/local/apache
TOMCAT_HOME=/usr/local/tomcat
APACHE_ERROR_LOG=${APACHE_HOME}/logs/error_log
TOMCAT_LOG=${TOMCAT_HOME}/logs/catalina.out
APACHE_STATUS=`curl -s http://127.0.0.1:80/`
TOMCAT_STATUS=`curl -s http://127.0.0.1:8080/`

# Log Format
DATATIME=`date '+%a %b %d %H:%M:%S %Y'`

######################################
APACHE_MONITOR=YES
TOMCAT_MONITOR=YES
######################################
APACHE_TOMCAT_MONITOR=YES
######################################
